services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    container_name: php_apache_app